### ISSUE TITLE
What's happening here? What should I do?

### ISSUE THREAD

**Issue by yhz5256** [chenxinpeng/SSD_scene_text_detection#16]
/home/yang/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/yang/data/scenetext/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/yang/data/VOCdevkit/ /home/yang/data/scenetext/test.txt /home/yang/data/VOCdevkit/scenetext/lmdb/scenetext_test_lmdb
Traceback (most recent call last):
  File "/home/yang/caffe/scripts/create_annoset.py", line 159, in <module>
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
/home/yang/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/yang/data/scenetext/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/yang/data/VOCdevkit/ /home/yang/data/scenetext/trainval.txt /home/yang/data/VOCdevkit/scenetext/lmdb/scenetext_trainval_lmdb
Traceback (most recent call last):
  File "/home/yang/caffe/scripts/create_annoset.py", line 159, in <module>
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by bobandjack** [comment]
Hello, did you get the ICDAR 2011 dataset ? I couldn't download it bacause of server problem. If possible, can you send me the dataset(upc.zihaolu@gmial.com)? Thank you in advance !

**Comment by bobandjack** [comment]
Hello, did you get the ICDAR 2011 dataset ? I couldn't download it bacause of server problem. If possible, can you send me the dataset(upc.zihaolu@gmail.com)? Thank you in advance !

**Comment by qaz3014** [comment]
Check your convert_annoset.exe path in caffe/script/create_annoset.py should solve the problem.
